name: "Github Actions Weather Bot"

on:
    push:
  #  schedule:
   #     - cron: '5 20 * * *'

jobs:
    bot:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: "Install node"
              uses: actions/setup-node@v1
            - name: "Install NPM dependecies"
              run: npm install 
            - name: "Run code"
              run: node index.js
              env:
                WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN}}
                TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN}}
                TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID}}
